version: "3.8"

services:
  postgres:
    container_name: postgres_database
    image: postgres:13
    environment:
      POSTGRES_DB: postgresql_salesapi
      POSTGRES_USER: postgresql_salesapi_user
      POSTGRES_PASSWORD: Senha@123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    container_name: mongodb_database
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ferdzagenciadigital
      MONGO_INITDB_ROOT_PASSWORD: NT85KnuJCKp2hK-
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  postgres_data:
  mongo_data:
